apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8sAI.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "k8sAI.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "k8sAI.name" . }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  type: {{ .Values.service.type }}
